### PR TITLE
frontend: delete dangling slash to avoid redirects

### LINKED ISSUE #147: fixup redirects for `/review`
```
backend_1   | INFO:     10.89.0.5:58910 - "GET /review/ HTTP/1.1" 307 Temporary Redirect
backend_1   | INFO:     10.89.0.5:58910 - "GET /review HTTP/1.1" 200 OK

backend_1   | INFO:     10.89.0.5:58910 - "POST /frontend/review/ HTTP/1.1" 307 Temporary Redirect
backend_1   | INFO:     10.89.0.5:58910 - "POST /frontend/review HTTP/1.1" 200 OK

backend_1   | INFO:     10.89.0.5:58912 - "POST /frontend/review/ HTTP/1.1" 307 Temporary Redirect
backend_1   | INFO:     10.89.0.5:58912 - "POST /frontend/review HTTP/1.1" 200 O
```

we should use the `/review` link instead of `/review/` to avoid these pointless redirects

### PR DESCRIPTION
**Pull request by nikromen**
Fix #147

### CODE REVIEW

**Review by TomasTomecek — APPROVED** [review]
Thanks! This definitely takes care of the form submit though I'm also still seeing that we link from the menu to `/review/` instead of `/review`: not sure if this is coming from our templates or fastapi.

**Comment by TomasTomecek** [comment]
pic:
image

**Comment by nikromen** [comment]
fixed, PTAL @TomasTomecek

**Review by TomasTomecek — APPROVED** [review]
Sweet, thanks Jirko! Let's go :rocket:

**Pull request merged**
