### PR TITLE
frontend: always calculate the snippet indexes from the beginning

### PR DESCRIPTION
**Pull request by FrostyX**
We have been collecting incorrect indexes. They aren't calculated from the end of the log but rather from the end of the previous node.

I am currently working on fixing our collected data.

### CODE REVIEW

**Comment by nikromen** [comment]
looking good so far, I checked the indexes on chromium and firefox

**Comment by TomasTomecek** [comment]
> We have been collecting incorrect indexes. They aren't calculated from the end of the log but rather from the end of the previous node.
> 
> I am currently working on fixing our collected data.

does this mean that some of our data may be wrong?

**Review by TomasTomecek — APPROVED** [review]
I can honestly say that I verified it now correctly works in Chrome. Because I accidentally checked out another PR where it was broken, then I correctly checked out this one and suddenly the indexes were right :)

```
$ podman exec a79b212b15f8 cat /persistent/results/2024-03-22/copr/7197868/1711110203.json > asdw.json

$ ipython3
Python 3.12.2 (main, Feb  7 2024, 00:00:00) [GCC 14.0.1 20240127 (Red Hat 14.0.1-0)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pathlib

In [2]: import json

In [3]: p = pathlib.Path("./asdw.json")

In [4]: j = json.loads(p.read_text())

In [5]: c = j["logs"]["builder-live.log"]["content"]

In [6]: for s in j["logs"]["builder-live.log"]["snippets"]:\
   ...:   print(f"'{c[s['start_index']:s['end_index']]}'\n'{s['user_comment']}'\n======")
'
Start: chroot in'
'start:'
======
'
E   ModuleNotFoundError: No module named 'telnetli'
'E Module'
======
```

Those were the exact lines I selected.

@FrostyX++ for spotting it and resolving it so precisely

**Review by jkonecny12 — APPROVED** [review]
I also verified this on Brave 1.64.109 . Without this patch the submitted snippets are broken with this patch it works good.

Thanks for the fix.

P.S.: I'm not able to verify code validity just testing.

**Comment by nikromen** [comment]
Thanks everybody for the reviews! It works for the most cases. However, there are 2 issues:

- 1 issue is small - the indexes are shifted by 2 or 1 - not a big deal, the context still remains
- 2 issue is however worse - if you scroll around the log and add a few snippets and then delete some of them, the next snippet indexes are wrong - with 100% reproducibility if you add snippet from the very end of the log. I think this may be caused by the first issue (the index overflows due to the indexes shift?)

**Comment by TomasTomecek** [comment]
> Thanks everybody for the reviews! It works for the most cases. However, there are 2 issues:
> 
> * 1 issue is small - the indexes are shifted by 2 or 1 - not a big deal, the context still remains
> * 2 issue is however worse - if you scroll around the log and add a few snippets and then delete some of them, the next snippet indexes are wrong - with 100% reproducibility if you add snippet from the very end of the log. I think this may be caused by the first issue (the index overflows due to the indexes shift?)

*naive thinking*: how about disabling removals?

**Comment by nikromen** [comment]
as per chat in slack - merging this to release this fix ASAP and deal with the edgecase later - #117

**Comment by nikromen** [comment]
> naive thinking: how about disabling removals?

That would significantly lower the user experience, potentially lowering the feedbacks we get :/ I used this feature several times. In case I'll need to close it and fill it once again (as normal user) I'd probably left it without giving feedback

**Pull request merged**
