### PR TITLE
add demo video to the first page of website

### PR DESCRIPTION
**Pull request by xsuchy**

### CODE REVIEW

**Comment by FrostyX** [comment]
For some reason, the gif doesn't appear when I try to run this.

Screenshot_2024-06-28_15-13-03

**Comment by FrostyX** [comment]
Also, what do you think about mentioning the youtube video in some sentence below the gif?

**Comment by xsuchy** [comment]
> Also, what do you think about mentioning the youtube video in some sentence below the gif?

I want to mention on Documentation page (and do it in separate PR).

And I think that it may confuse people when a-href will point to different video than what they see.

**Comment by xsuchy** [comment]
> For some reason, the gif doesn't appear when I try to run this.

Strange. It worked for me when I tried `npx shadow-cljs watch app`. Any idea what can be wrong?

**Comment by xsuchy** [comment]
I changed relative link to absolute. Can you try now?

**Comment by FrostyX** [comment]
Maybe this is my error? I cannot even open the gif image

Screenshot_2024-06-28_16-24-43

However, the same error happens when I try to open the file in `main`.
I'll try to debug later.

**Comment by xsuchy** [comment]
Note that in this PR I moved the file to different directory.

**Comment by FrostyX** [comment]
Probably an error on my side then? Let's merge and see if it works in production.

**Pull request merged**
